### ISSUE TITLE
Cannot assign to read only property 'authData' of object '#<Object>'

### ISSUE THREAD

**Issue by OR13** [truffle-box/react-auth-box#1]
Remove this line:

this.props.authData = authData

in Dashboard.js...

it causes:

TypeError: Cannot assign to read only property 'authData' of object '#<Object>'

**Comment by DavidBurela** [comment]
I'm getting the same issue

**Comment by DiscRiskandBisque** [comment]
Thanks for the issue! Catching up on these, it's since been adjusted based on the same issue in another box. Going to close for now, but please re-open if the current master still has this issue.
