### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by armova** [truffle-box/react-auth-box#11]
httpprovider.js:61 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

How can I get rid of this by setting web3 to async?

Have tried by passing a callback function in the call to web3's functions as suggested by the web3 docs but is not working.

Will appreciate any help.

**Comment by rstormsf** [comment]
I had this issue when I had chrome redux devtool enabled.

**Comment by armova** [comment]
@rstormsf thanks! it works
