### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by varvarasd** [truffle-box/react-auth-box#28]
I've sign up and login button doesn't do anything. Is there anything I'm missing?
I've added a random name on signup and nothing happens when I click login. I do get the popup from MetaMask to submit the transaction once I click signup, i submit then nothing happens and login doesn't do anything... 

Any suggestions are greatly appreciated.
Many thanks

**Comment by elie222** [comment]
Yes, there's an error in the console:
```
errors.js:35 Uncaught (in promise) Error: Failed to fetch
    at Object.InvalidResponse (errors.js:35)
    at requestmanager.js:86
    at inpage.js:9909
    at completeRequest (inpage.js:9960)
    at inpage.js:683
    at replenish (inpage.js:1203)
    at iterateeCallback (inpage.js:1193)
    at inpage.js:1168
    at inpage.js:9837
    at inpage.js:9933
```

This is the culprit line:
```
authentication.deployed().then(function(instance) {
```

**Comment by elie222** [comment]
I finally got it working once I set up metamask locally correctly.

**Comment by varvarasd** [comment]
Yes. I've restarted the browser and the truffle develop session and works fine. I'm suspecting the metamask needs to synchronize with the truffle to work.
Cheers
