### ISSUE TITLE
Injected web3 is not properly detected

### ISSUE THREAD

**Issue by apackin** [truffle-box/react-auth-box#6]
When using this with MetaMask the check for `typeof web3 !== 'undefined'` fails in getWeb3.js causing fallback to local web3

### Error Received
console.log of 'No web3 instance injected, using Local web3.' even though MetaMask is enabled.

### Fix: 
Replace usage of the local `web3` with `window.web3` IE:

```
window.addEventListener('load', function(dispatch) {
    var results

    // Checking if Web3 has been injected by the browser (Mist/MetaMask)
    if (typeof window.web3 !== 'undefined') {
      // Use Mist/MetaMask's provider.
      results = {
        web3Instance: new Web3(window.web3.currentProvider)
      }

      console.log('Injected web3 detected.');

      resolve(store.dispatch(web3Initialized(results)))
```

https://github.com/apackin/groupBuy/commit/a6881c53fa1d0271a14766a86e1e6d9dd25086fb

**Comment by DiscRiskandBisque** [comment]
Thank you for formatting this so well! It's now fixed.
